version: "3.5"

services:
  tests:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    command:
      - "/root/py/bin/pytest"
    depends_on:
      - app

  app:
    image: ubuntu:23.04
    platform: linux/amd64
    command: ["bash", "-c", "./tester.so 0.0.0.0 4000"]
    working_dir: /app
    volumes:
      - ./:/app
